### ISSUE TITLE
Explore making the GitLab runner `cypress` tests instead of `jest`

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-gitlab-runner#72]
### Describe what should be investigated or refactored
Our current journey tests are written in `jest` but it _may_ be nicer to explore `cypress` to be able to navigate the web interface of GitLab and ensure that it also works correctly.  `cypress` may also make the waits and retries easier as well.

### Links to any relevant code
https://github.com/defenseunicorns/uds-package-gitlab-runner/tree/main/test

### Additional context
This came out of reflections for how this works with GitLab and the decode slashes issues here: https://github.com/defenseunicorns/uds-core/issues/288

**Comment by zachariahmiller** [comment]
Or playwright?

**Comment by zachariahmiller** [comment]
Additional context on above. UDS Core team is currently using cypress for things ( i think just keycloak) after running into issues trying to use playwright with custom certs. My understanding is the pivot to cypress was just in the interest of time, not necessarily based on merits. It sounds like for now those test are very limited integration tests and there are discussions around doing more indepth testing (MFA, email verification, etc) at which time they will probably reevaluate playwright. 

We could probably take the same approach here. On the other hand, we could maybe take a stab at getting playwright working in the first place with the custom certs and evaluate since we will probably have more of this type of testing that we need to do across SWF applications.
